# Logo (Font Awesome Class)
fa_logo: fa-cube

# Header
menu:
  Home: /
  Archives: /archives
  # About: /about.html
  # Tags: /tags
  # Categories: /categories
  # Contact: /contact.html

# Default post title
default_post_title: Link

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname:

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
# twitter_url: https://twitter.com/?lang=en
# facebook_url: https://www.facebook.com/
# instagram_url: https://www.instagram.com/
# dribble_url: https://dribbble.com/
github_url: https://github.com/Linkontoask
# googleplus_url: https://plus.google.com/
# behance_url: https://www.behance.net/
# fivehundredpx_url: https://500px.com/
email_url: link19970507@gmail.com
site_url: https://linkorg.club
# rss_url: \#

# Footer About Text
footer_about: "是一个相信选择大于努力的人，更新一些关于工作的博客"

# Footer Copyright Line
footer_copyright: "@Link. All right reserved | Design & Hexo"

